### ISSUE TITLE
Forcing reauthentication

### ISSUE THREAD

**Issue by mikael-linden** [ga4gh/data-security#19]
**Conformance for Embedded Token Signatories** section:
_...the Embedded Token Signatory could set the exp to 14 days into the future in order to force a user authentication flow to be redone if a downstream Claim Clearinghouse is still interested in using such a claim after this period elapses_

**Claim Source Revokes Claim** section:
_Expiry timestamps would require users to log in occasionally via an Broker in order to refresh claims._

I don't think a new log in is necessarily needed if an (access) token expires. For expired access token, a refresh token can be used (by the client). For expired document token, whatever means supported by the Embedded Token Signatory can be used (this spec imposes no requirement for the the user to ever log in to an Embedded Token Signatory).

**Comment by davidbernick** [comment]
How would you suggest changing both these section @mikael-linden ?

**Comment by cdvoisin** [comment]
It is a non-normative example, so yes the example could have used a refresh token instead although leaves more confusion since it leaves the question of "why can't I just ask /userinfo for the latest, and let the access token be revoked without the need for a refresh token?" In the example given, it shows how you can force a new user session. However, refresh tokens still is a totally reasonable alternative and may make sense in systems that are designed with refresh tokens in mind (over access token polling).

So if you prefer, feel free to switch the example to refresh tokens. I'm good with that. Forced login example can be (and perhaps should be) a landing page example anyway.
